name: Validate Renovate Config

permissions:
  contents: read

on:
  pull_request: {}

jobs:
  validate-renovate-config:
    name: Validate renovate config
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:44.46.5@sha256:668ba57a610f8bb22a43c6f4271e7855e2d3cf180f85f88bdaf981f04967386d
      options: --user root
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: renovate --version
      - run: renovate-config-validator default.json5
      - run: renovate-config-validator .github/renovate.json5
