name: Validate Renovate Config

permissions:
  contents: read

on:
  pull_request: {}

jobs:
  validate-renovate-config:
    name: Validate renovate config
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:43.242.2@sha256:9f9a0b9a4b5da3d9634493635e9fc4bcc196a9fcd45299af68d015ddd3f3987f
      options: --user root
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: renovate --version
      - run: renovate-config-validator default.json5
      - run: renovate-config-validator .github/renovate.json5
